import{a as b,S as L,i as c}from"./assets/vendor-D0cagnvz.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&o(r)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const v="47491725-6916c20f65c7c72c223d91484",w="https://pixabay.com/api/";let d=1;async function u(s){const i=`${w}?key=${v}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&page=${d}&per_page=15`;try{return(await b.get(i)).data}catch(n){throw console.error("Error fetching images:",n),n}}function f(){d+=1}function q(){d=1}const S=new L(".gallery a");function h(s){const i=document.querySelector(".gallery"),n=s.map(({webformatURL:o,largeImageURL:e,tags:t,likes:r,views:l,comments:g,downloads:p})=>`
        <a href="${e}" class="gallery-item">
          <img src="${o}" alt="${t}" />
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${r}</p>
            <p class="info-item"><b>Views:</b> ${l}</p>
            <p class="info-item"><b>Comments:</b> ${g}</p>
            <p class="info-item"><b>Downloads:</b> ${p}</p>
          </div>
        </a>
      `).join("");i.insertAdjacentHTML("beforeend",n),S.refresh()}function a(){const s=document.querySelector(".gallery");s.innerHTML="",c.error({title:"Sorry",message:"There are no images matching your search query. Please try again!"})}function m(){document.querySelector(".loader").classList.remove("hidden")}function y(){document.querySelector(".loader").classList.add("hidden")}document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".search-form"),i=document.querySelector(".search-input"),n=document.querySelector(".gallery"),o=document.createElement("button");o.textContent="Load more",o.classList.add("load-more","hidden"),document.body.appendChild(o),o.addEventListener("click",async()=>{var t;const e=i.value.trim();m();try{const r=await u(e);if(r.hits.length===0){a();return}h(r.hits),f(),r.totalHits<=n.children.length&&(o.classList.add("hidden"),c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}));const l=((t=n.children[0])==null?void 0:t.offsetHeight)*2||0;window.scrollBy({top:l,behavior:"smooth"}),setTimeout(()=>{s.scrollIntoView({behavior:"smooth",block:"start"})},500)}catch{a()}finally{y()}}),s.addEventListener("submit",async e=>{e.preventDefault();const t=i.value.trim();if(t===""){c.warning({title:"Warning",message:"Please enter a search term."});return}n.innerHTML="",q(),o.classList.add("hidden"),m();try{const r=await u(t);if(r.hits.length===0){a();return}h(r.hits),f(),o.classList.remove("hidden"),r.totalHits<=15&&(o.classList.add("hidden"),c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})),setTimeout(()=>{s.scrollIntoView({behavior:"smooth",block:"start"})},500)}catch{a()}finally{y()}})});
//# sourceMappingURL=index.js.map
