import{S as d,i as f}from"./assets/vendor-5ObWk2rO.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const m="47491725-6916c20f65c7c72c223d91484",h="https://pixabay.com/api/";function y(o){const n=`${h}?key=${m}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(n).then(r=>{if(!r.ok)throw new Error(`HTTP error! Status: ${r.status}`);return r.json()}).catch(r=>{throw console.error("Error fetching images:",r),r})}const g=new d(".gallery a");function p(o){const n=document.querySelector(".gallery");if(n.innerHTML="",o.length===0){c();return}const r=o.map(({webformatURL:s,largeImageURL:e,tags:t,likes:i,views:a,comments:l,downloads:u})=>`
        <a href="${e}" class="gallery-item">
          <img src="${s}" alt="${t}" />
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${i}</p>
            <p class="info-item"><b>Views:</b> ${a}</p>
            <p class="info-item"><b>Comments:</b> ${l}</p>
            <p class="info-item"><b>Downloads:</b> ${u}</p>
          </div>
        </a>
      `).join("");n.insertAdjacentHTML("beforeend",r),g.refresh()}function c(){const o=document.querySelector(".gallery");o.innerHTML="",f.error({title:"Sorry",message:"There are no images matching your search query. Please try again!"})}function L(){document.querySelector(".loader").classList.remove("hidden")}function b(){document.querySelector(".loader").classList.add("hidden")}document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector(".search-form"),n=document.querySelector(".search-input");o.addEventListener("submit",async r=>{r.preventDefault();const s=n.value.trim();if(s===""){iziToast.warning({title:"Warning",message:"Please enter a search term."});return}const e=document.querySelector(".gallery");e.innerHTML="",L();try{const t=await y(s);if(t.hits.length===0){c();return}p(t.hits)}catch{c()}finally{b()}})});
//# sourceMappingURL=index.js.map
