import{a as d,S as f,i as m}from"./assets/vendor-D0cagnvz.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const p="47491725-6916c20f65c7c72c223d91484",y="https://pixabay.com/api/";let g=1;async function h(t){const o=`${y}?key=${p}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${g}&per_page=15`;try{return(await d.get(o)).data}catch(n){throw console.error("Error fetching images:",n),n}}const L=new f(".gallery a");function b(t){const o=document.querySelector(".gallery");if(o.innerHTML="",t.length===0){a();return}const n=t.map(({webformatURL:s,largeImageURL:e,tags:r,likes:i,views:c,comments:l,downloads:u})=>`
        <a href="${e}" class="gallery-item">
          <img src="${s}" alt="${r}" />
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${i}</p>
            <p class="info-item"><b>Views:</b> ${c}</p>
            <p class="info-item"><b>Comments:</b> ${l}</p>
            <p class="info-item"><b>Downloads:</b> ${u}</p>
          </div>
        </a>
      `).join("");o.insertAdjacentHTML("beforeend",n),L.refresh()}function a(){const t=document.querySelector(".gallery");t.innerHTML="",m.error({title:"Sorry",message:"There are no images matching your search query. Please try again!"})}function S(){document.querySelector(".loader").classList.remove("hidden")}function $(){document.querySelector(".loader").classList.add("hidden")}document.addEventListener("DOMContentLoaded",()=>{const t=document.querySelector(".search-form"),o=document.querySelector(".search-input");t.addEventListener("submit",async n=>{n.preventDefault();const s=o.value.trim();if(s===""){iziToast.warning({title:"Warning",message:"Please enter a search term."});return}const e=document.querySelector(".gallery");e.innerHTML="",S();try{const r=await h(s);if(r.hits.length===0){a();return}b(r.hits)}catch{a()}finally{$()}})});
//# sourceMappingURL=index.js.map
